[services.api-gateway]
builder = "dockerfile"
dockerfilePath = "apps/api-gateway/Dockerfile"
watchPatterns = [
  "apps/api-gateway/**",
  "libs/resume-data/**",
  "package.json",
  "pnpm-lock.yaml"
]

[services.frontend]
builder = "dockerfile"
dockerfilePath = "apps/frontend/Dockerfile"
watchPatterns = [
  "apps/frontend/**",
  "libs/spurlock-ui/**",
  "package.json",
  "pnpm-lock.yaml"
]

[services.storybook]
builder = "dockerfile"
dockerfilePath = "libs/spurlock-ui/Dockerfile"
watchPatterns = [
  "libs/spurlock-ui/**",
  "package.json",
  "pnpm-lock.yaml"
]
