[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm', 'chromium']

[phases.install]
cmds = ['cd ../.. && pnpm install --frozen-lockfile']

[phases.build]
cmds = ['cd ../.. && pnpm build:api']

[start]
cmd = 'cd ../.. && PUPPETEER_EXECUTABLE_PATH=$(which chromium) node dist/apps/api-gateway/main.js'
